name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:  
  push:
    branches: ['master']
  pull_reqest:
   branches: ['master']
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: 18
    steps:
       - uses: actions/checkout@v4
       - name: Staring Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v4
         with: 
            node-version: ${{ matrix.node-version }}
      - name: install modules
      run: npm install
      - name: build prod production
      run: npm run build:prod
      - name: linting typescript
      run: npm run lint:ts
      - name: linting css
      run: npm run lint:scss
      - name: unit testing
      run: npm run test:unit